### ISSUE TITLE
file class

### ISSUE THREAD

**Issue by jimmywarting** [za-creature/cf-emu#1]
https://github.com/za-creature/cf-emu/blob/b342d1f419208b8857257ad619253d30a850eafb/cf-emu/lib/multipart.js#L11-L32

fetch-blob@v3 got built in File class now

```js
import File from 'fetch-blob/file.js'
```

**Comment by za-creature** [comment]
Thanks, I am aware of that.

While just recently published, this code is fairly old, dating back to the workers beta and targeting node.js 8 and IIRC, node-fetch v3 (or one of its dependencies) did not work correctly on that version.

I plan to drop support and update all dependencies (if only to get rid of the security nag screen on github) but I haven't got around to doing that just yet.

I'll keep this open until such a time when a new major version is published only targeting 10+ (or even 12+, I'm not sure what the LTS plan for node is looking like these days).

Cheers and thanks for the module!

**Comment by za-creature** [comment]
Closing this because the long term plan is to migrate to the native fetch implementation, available since (at least) v18
